-- SHARED. Pack, use and type for every shell, so the Shells tab can be searched by words like
-- "warehouse" or "office". Shells missing here still show, with no type.
ShellMeta = {
    ['loft_shell'] = { pack = 'Fury pack', use = 'home', type = 'loft', furnished = true, note = 'one big room, open plan' },
    ['cozy_shell_f'] = { pack = 'Fury pack', use = 'home', type = 'apartment', furnished = true, note = 'small, warm' },
    ['cozy_shell_u'] = { pack = 'Fury pack', use = 'home', type = 'apartment', furnished = false, note = '' },
    ['skyview_shell_f'] = { pack = 'Fury pack', use = 'home', type = 'loft', furnished = true, note = 'sunroof loft' },
    ['skyview_shell_u'] = { pack = 'Fury pack', use = 'home', type = 'loft', furnished = false, note = '' },
    ['jap_shell_f'] = { pack = 'Fury pack', use = 'home', type = 'loft', furnished = true, note = 'Japanese style' },
    ['jap_shell_u'] = { pack = 'Fury pack', use = 'home', type = 'loft', furnished = false, note = '' },
    ['starter_shell_f'] = { pack = 'Fury pack', use = 'home', type = 'apartment', furnished = true, note = 'starter, low tier' },
    ['starter_shell_u'] = { pack = 'Fury pack', use = 'home', type = 'apartment', furnished = false, note = '' },
    ['midshell1_f'] = { pack = 'Fury pack', use = 'home', type = 'apartment', furnished = true, note = 'mid tier' },
    ['midshell1_u'] = { pack = 'Fury pack', use = 'home', type = 'apartment', furnished = false, note = '' },
    ['midshell2_f'] = { pack = 'Fury pack', use = 'home', type = 'apartment', furnished = true, note = 'mid tier' },
    ['midshell2_u'] = { pack = 'Fury pack', use = 'home', type = 'apartment', furnished = false, note = '' },
    ['fury_shell04'] = { pack = 'Fury pack', use = 'home', type = 'apartment', furnished = true, note = 'GTA Online apartment' },
    ['fury_shell06'] = { pack = 'Fury pack', use = 'home', type = 'apartment', furnished = true, note = 'GTA Online apartment' },
    ['fury_shell07'] = { pack = 'Fury pack', use = 'home', type = 'apartment', furnished = true, note = 'GTA Online apartment' },
    ['fury_shell08'] = { pack = 'Fury pack', use = 'home', type = 'apartment', furnished = true, note = 'GTA executive apartment' },
    ['fury_shell09'] = { pack = 'Fury pack', use = 'home', type = 'apartment', furnished = true, note = 'GTA executive apartment' },
    ['fury_shell01_f'] = { pack = 'Fury pack V2', use = 'home', type = 'apartment', furnished = true, note = '' },
    ['fury_shell01_u'] = { pack = 'Fury pack V2', use = 'home', type = 'apartment', furnished = false, note = '' },
    ['fury_shell02_f'] = { pack = 'Fury pack V2', use = 'home', type = 'apartment', furnished = true, note = '' },
    ['fury_shell02_u'] = { pack = 'Fury pack V2', use = 'home', type = 'apartment', furnished = false, note = '' },
    ['fury_shell03_f'] = { pack = 'Fury pack V2', use = 'home', type = 'apartment', furnished = true, note = '' },
    ['fury_shell03_u'] = { pack = 'Fury pack V2', use = 'home', type = 'apartment', furnished = false, note = '' },
    ['fury_shell04_f'] = { pack = 'Fury pack V2', use = 'home', type = 'apartment', furnished = true, note = '' },
    ['fury_shell04_u'] = { pack = 'Fury pack V2', use = 'home', type = 'apartment', furnished = false, note = '' },
    ['fury_shell05_f'] = { pack = 'Fury pack V2', use = 'home', type = 'apartment', furnished = true, note = '' },
    ['fury_shell05_u'] = { pack = 'Fury pack V2', use = 'home', type = 'apartment', furnished = false, note = '' },
    ['envi_shell_01_furnished'] = { pack = 'Envi starter', use = 'home', type = 'apartment', furnished = true, note = 'free, your GitHub' },
    ['envi_shell_01_empty'] = { pack = 'Envi starter', use = 'home', type = 'apartment', furnished = false, note = '' },
    ['envi_shell_02_furnished'] = { pack = 'Envi starter', use = 'home', type = 'apartment', furnished = true, note = '' },
    ['envi_shell_02_empty'] = { pack = 'Envi starter', use = 'home', type = 'apartment', furnished = false, note = '' },
    ['envi_shell_03_furnished'] = { pack = 'Envi starter', use = 'home', type = 'apartment', furnished = true, note = '' },
    ['envi_shell_03_empty'] = { pack = 'Envi starter', use = 'home', type = 'apartment', furnished = false, note = '' },
    ['t1_furn_shell'] = { pack = 'Lynx', use = 'home', type = 'apartment', furnished = true, note = 'tier 1, free' },
    ['t1_unfurn_shell'] = { pack = 'Lynx', use = 'home', type = 'apartment', furnished = false, note = '' },
    ['t2_furn_shell'] = { pack = 'Lynx', use = 'home', type = 'apartment', furnished = true, note = 'tier 2' },
    ['t2_unfurn_shell'] = { pack = 'Lynx', use = 'home', type = 'apartment', furnished = false, note = '' },
    ['t3_furn_shell'] = { pack = 'Lynx', use = 'home', type = 'apartment', furnished = true, note = 'tier 3' },
    ['t3_unfurn_shell'] = { pack = 'Lynx', use = 'home', type = 'apartment', furnished = false, note = '' },
    ['shell_frankaunt'] = { pack = 'K4MB1 starter', use = 'home', type = 'house', furnished = true, note = 'Franklin\'s aunt\'s house' },
    ['shell_lester'] = { pack = 'K4MB1 starter', use = 'home', type = 'house', furnished = true, note = 'Lester\'s house' },
    ['shell_michael'] = { pack = 'K4MB1 starter', use = 'home', type = 'house', furnished = true, note = 'Michael\'s mansion' },
    ['shell_trevor'] = { pack = 'K4MB1 starter', use = 'home', type = 'trailer', furnished = true, note = 'Trevor\'s trailer' },
    ['shell_ranch'] = { pack = 'K4MB1 starter', use = 'home', type = 'house', furnished = true, note = 'ranch house' },
    ['shell_trailer'] = { pack = 'K4MB1 starter', use = 'home', type = 'trailer', furnished = true, note = 'plain trailer (motorhome pack copy)' },
    ['shell_v16low'] = { pack = 'K4MB1 starter', use = 'home', type = 'apartment', furnished = true, note = 'Eclipse Towers, low tier (motorhome pack copy)' },
    ['shell_v16mid'] = { pack = 'K4MB1 starter', use = 'home', type = 'apartment', furnished = true, note = 'Eclipse Towers, mid tier (motorhome pack copy)' },
    ['furnitured_midapart'] = { pack = 'K4MB1 starter', use = 'home', type = 'apartment', furnished = true, note = 'mid apartment' },
    ['standardmotel_shell'] = { pack = 'K4MB1 starter', use = 'home', type = 'motel room', furnished = true, note = 'also used by the motel idea' },
    ['modernhotel_shell'] = { pack = 'K4MB1 starter', use = 'home', type = 'hotel room', furnished = true, note = '' },
    ['shell_office1'] = { pack = 'K4MB1 starter', use = 'work', type = 'office', furnished = true, note = 'first office shell' },
    ['shell_store1'] = { pack = 'K4MB1 starter', use = 'work', type = 'store', furnished = true, note = '' },
    ['shell_warehouse1'] = { pack = 'K4MB1 starter', use = 'work', type = 'warehouse', furnished = true, note = '' },
    ['shell_garagem'] = { pack = 'K4MB1 starter', use = 'work', type = 'garage', furnished = true, note = '' },
    ['container_shell'] = { pack = 'K4MB1 starter', use = 'work', type = 'container', furnished = true, note = 'shipping container (motorhome pack copy)' },
    ['k4_banham1_shell'] = { pack = 'K4MB1 Main', use = 'home', type = 'house', furnished = false, note = '' },
    ['k4_banham2_shell'] = { pack = 'K4MB1 Main', use = 'home', type = 'house', furnished = false, note = '' },
    ['k4_highend1_shell'] = { pack = 'K4MB1 Main', use = 'home', type = 'apartment', furnished = false, note = '' },
    ['k4_highend2_shell'] = { pack = 'K4MB1 Main', use = 'home', type = 'apartment', furnished = false, note = '' },
    ['k4_highend3_shell'] = { pack = 'K4MB1 Main', use = 'home', type = 'apartment', furnished = false, note = '' },
    ['k4_highend4_shell'] = { pack = 'K4MB1 Main', use = 'home', type = 'apartment', furnished = false, note = '' },
    ['k4_highend5_shell'] = { pack = 'K4MB1 Main', use = 'home', type = 'apartment', furnished = false, note = '' },
    ['k4_highend6_shell'] = { pack = 'K4MB1 Main', use = 'home', type = 'apartment', furnished = false, note = '' },
    ['k4_highend7_shell'] = { pack = 'K4MB1 Main', use = 'home', type = 'apartment', furnished = false, note = '' },
    ['k4_highend8_shell'] = { pack = 'K4MB1 Main', use = 'home', type = 'apartment', furnished = false, note = '' },
    ['k4_highend9_shell'] = { pack = 'K4MB1 Main', use = 'home', type = 'apartment', furnished = false, note = '' },
    ['k4_highend10_shell'] = { pack = 'K4MB1 Main', use = 'home', type = 'apartment', furnished = false, note = '' },
    ['k4_lester1_shell'] = { pack = 'K4MB1 Main', use = 'home', type = 'house', furnished = false, note = '' },
    ['k4_lester2_shell'] = { pack = 'K4MB1 Main', use = 'home', type = 'house', furnished = false, note = '' },
    ['k4_michael2_shell'] = { pack = 'K4MB1 Main', use = 'home', type = 'mansion', furnished = false, note = '' },
    ['k4_michael_shell'] = { pack = 'K4MB1 Main', use = 'home', type = 'mansion', furnished = false, note = '' },
    ['k4_ranch1_shell'] = { pack = 'K4MB1 Main', use = 'home', type = 'house', furnished = false, note = '' },
    ['k4_ranch2_shell'] = { pack = 'K4MB1 Main', use = 'home', type = 'house', furnished = false, note = '' },
    ['k4_shell_medium1'] = { pack = 'K4MB1 Main', use = 'home', type = 'apartment', furnished = false, note = '' },
    ['k4_shell_medium2'] = { pack = 'K4MB1 Main', use = 'home', type = 'apartment', furnished = false, note = '' },
    ['k4_shell_medium3'] = { pack = 'K4MB1 Main', use = 'home', type = 'apartment', furnished = false, note = '' },
    ['k4_shell_medium4'] = { pack = 'K4MB1 Main', use = 'home', type = 'apartment', furnished = false, note = '' },
    ['k4_shell_medium5'] = { pack = 'K4MB1 Main', use = 'home', type = 'apartment', furnished = false, note = '' },
    ['k4_shell_medium6'] = { pack = 'K4MB1 Main', use = 'home', type = 'apartment', furnished = false, note = '' },
    ['k4_trailer1_shell'] = { pack = 'K4MB1 Main', use = 'home', type = 'trailer', furnished = false, note = '' },
    ['k4_trailer2_shell'] = { pack = 'K4MB1 Main', use = 'home', type = 'trailer', furnished = false, note = '' },
    ['k4_trevor1_shell'] = { pack = 'K4MB1 Main', use = 'home', type = 'trailer', furnished = false, note = '' },
    ['k4_trevor2_shell'] = { pack = 'K4MB1 Main', use = 'home', type = 'trailer', furnished = false, note = '' },
    ['k4_v16low1_shell'] = { pack = 'K4MB1 Main', use = 'home', type = 'apartment', furnished = false, note = '' },
    ['k4_v16low2_shell'] = { pack = 'K4MB1 Main', use = 'home', type = 'apartment', furnished = false, note = '' },
    ['k4_v16mid1_shell'] = { pack = 'K4MB1 Main', use = 'home', type = 'apartment', furnished = false, note = '' },
    ['k4_v16mid2_shell'] = { pack = 'K4MB1 Main', use = 'home', type = 'apartment', furnished = false, note = '' },
    ['k4_v16mid3_shell'] = { pack = 'K4MB1 Main', use = 'home', type = 'apartment', furnished = false, note = '' },
    ['k4_v16mid4_shell'] = { pack = 'K4MB1 Main', use = 'home', type = 'apartment', furnished = false, note = '' },
    ['k4_westons1_shell'] = { pack = 'K4MB1 Main', use = 'home', type = 'house', furnished = false, note = '' },
    ['k4_westons2_shell'] = { pack = 'K4MB1 Main', use = 'home', type = 'house', furnished = false, note = '' },
    ['k4_westons3_shell'] = { pack = 'K4MB1 Main', use = 'home', type = 'house', furnished = false, note = '' },
    ['k4_westons4_shell'] = { pack = 'K4MB1 Main', use = 'home', type = 'house', furnished = false, note = '' },
    ['k4_classic1_shell'] = { pack = 'K4MB1 Premium', use = 'home', type = 'house', furnished = false, note = '' },
    ['k4_classic2_shell'] = { pack = 'K4MB1 Premium', use = 'home', type = 'house', furnished = false, note = '' },
    ['k4_classic3_shell'] = { pack = 'K4MB1 Premium', use = 'home', type = 'house', furnished = false, note = '' },
    ['k4_classic4_shell'] = { pack = 'K4MB1 Premium', use = 'home', type = 'house', furnished = false, note = '' },
    ['k4_classic5_shell'] = { pack = 'K4MB1 Premium', use = 'home', type = 'house', furnished = false, note = '' },
    ['k4_classic6_shell'] = { pack = 'K4MB1 Premium', use = 'home', type = 'house', furnished = false, note = '' },
    ['k4_hotel1_shell'] = { pack = 'K4MB1 Premium', use = 'home', type = 'hotel room', furnished = false, note = '' },
    ['k4_hotel2_shell'] = { pack = 'K4MB1 Premium', use = 'home', type = 'hotel room', furnished = false, note = '' },
    ['k4_hotel3_shell'] = { pack = 'K4MB1 Premium', use = 'home', type = 'hotel room', furnished = false, note = '' },
    ['k4_motel1_shell'] = { pack = 'K4MB1 Premium', use = 'home', type = 'motel room', furnished = false, note = '' },
    ['k4_motel2_shell'] = { pack = 'K4MB1 Premium', use = 'home', type = 'motel room', furnished = false, note = '' },
    ['k4_motel3_shell'] = { pack = 'K4MB1 Premium', use = 'home', type = 'motel room', furnished = false, note = '' },
    ['k4_richman1_shell'] = { pack = 'K4MB1 Premium', use = 'home', type = 'mansion', furnished = false, note = '' },
    ['k4_richman2_shell'] = { pack = 'K4MB1 Premium', use = 'home', type = 'mansion', furnished = false, note = '' },
    ['k4_richman3_shell'] = { pack = 'K4MB1 Premium', use = 'home', type = 'mansion', furnished = false, note = '' },
    ['k4_vwhouse1_shell'] = { pack = 'K4MB1 Premium', use = 'home', type = 'house', furnished = false, note = '' },
    ['k4_vwhouse2_shell'] = { pack = 'K4MB1 Premium', use = 'home', type = 'house', furnished = false, note = '' },
    ['k4_vwmansion1_shell'] = { pack = 'K4MB1 Premium', use = 'home', type = 'mansion', furnished = false, note = '' },
    ['k4_hotel1_furn'] = { pack = 'K4MB1 Furnished', use = 'home', type = 'hotel room', furnished = true, note = '' },
    ['k4_hotel2_furn'] = { pack = 'K4MB1 Furnished', use = 'home', type = 'hotel room', furnished = true, note = '' },
    ['k4_hotel3_furn'] = { pack = 'K4MB1 Furnished', use = 'home', type = 'hotel room', furnished = true, note = '' },
    ['k4_hotel4_furn'] = { pack = 'K4MB1 Furnished', use = 'home', type = 'hotel room', furnished = true, note = '' },
    ['k4_hotel5_furn'] = { pack = 'K4MB1 Furnished', use = 'home', type = 'hotel room', furnished = true, note = '' },
    ['k4_hotel6_furn'] = { pack = 'K4MB1 Furnished', use = 'home', type = 'hotel room', furnished = true, note = '' },
    ['k4_house1_furn'] = { pack = 'K4MB1 Furnished', use = 'home', type = 'house', furnished = true, note = '' },
    ['k4_house2_furn'] = { pack = 'K4MB1 Furnished', use = 'home', type = 'house', furnished = true, note = '' },
    ['k4_house3_furn'] = { pack = 'K4MB1 Furnished', use = 'home', type = 'house', furnished = true, note = '' },
    ['k4_house4_furn'] = { pack = 'K4MB1 Furnished', use = 'home', type = 'house', furnished = true, note = '' },
    ['k4_house5_furn'] = { pack = 'K4MB1 Furnished', use = 'home', type = 'house', furnished = true, note = '' },
    ['k4_house6_furn'] = { pack = 'K4MB1 Furnished', use = 'home', type = 'house', furnished = true, note = '' },
    ['k4_house7_furn'] = { pack = 'K4MB1 Furnished', use = 'home', type = 'house', furnished = true, note = '' },
    ['k4_house8_furn'] = { pack = 'K4MB1 Furnished', use = 'home', type = 'house', furnished = true, note = '' },
    ['k4_motel1_furn'] = { pack = 'K4MB1 Furnished', use = 'home', type = 'motel room', furnished = true, note = '' },
    ['k4_motel2_furn'] = { pack = 'K4MB1 Furnished', use = 'home', type = 'motel room', furnished = true, note = '' },
    ['k4_apa1_shell'] = { pack = 'K4MB1 Exclusive', use = 'home', type = 'apartment', furnished = false, note = '' },
    ['k4_apa2_shell'] = { pack = 'K4MB1 Exclusive', use = 'home', type = 'apartment', furnished = false, note = '' },
    ['k4_apa3_shell'] = { pack = 'K4MB1 Exclusive', use = 'home', type = 'apartment', furnished = false, note = '' },
    ['k4_house1_shell'] = { pack = 'K4MB1 Exclusive', use = 'home', type = 'house', furnished = false, note = '' },
    ['k4_house2_shell'] = { pack = 'K4MB1 Exclusive', use = 'home', type = 'house', furnished = false, note = '' },
    ['k4_house3_shell'] = { pack = 'K4MB1 Exclusive', use = 'home', type = 'house', furnished = false, note = '' },
    ['k4_house4_shell'] = { pack = 'K4MB1 Exclusive', use = 'home', type = 'house', furnished = false, note = '' },
    ['k4_house5_shell'] = { pack = 'K4MB1 Exclusive', use = 'home', type = 'house', furnished = false, note = '' },
    ['k4_house6_shell'] = { pack = 'K4MB1 Exclusive', use = 'home', type = 'house', furnished = false, note = '' },
    ['k4_house7_shell'] = { pack = 'K4MB1 Exclusive', use = 'home', type = 'house', furnished = false, note = '' },
    ['k4_house8_shell'] = { pack = 'K4MB1 Exclusive', use = 'home', type = 'house', furnished = false, note = '' },
    ['k4_house9_shell'] = { pack = 'K4MB1 Exclusive', use = 'home', type = 'house', furnished = false, note = '' },
    ['k4_house10_shell'] = { pack = 'K4MB1 Exclusive', use = 'home', type = 'house', furnished = false, note = '' },
    ['k4_house11_shell'] = { pack = 'K4MB1 Exclusive', use = 'home', type = 'house', furnished = false, note = '' },
    ['k4_house12_shell'] = { pack = 'K4MB1 Exclusive', use = 'home', type = 'house', furnished = false, note = '' },
    ['k4_house13_shell'] = { pack = 'K4MB1 Exclusive', use = 'home', type = 'house', furnished = false, note = '' },
    ['k4_house14_shell'] = { pack = 'K4MB1 Exclusive', use = 'home', type = 'house', furnished = false, note = '' },
    ['k4_loft1_shell'] = { pack = 'K4MB1 Exclusive', use = 'home', type = 'loft', furnished = false, note = '' },
    ['k4_loft2_shell'] = { pack = 'K4MB1 Exclusive', use = 'home', type = 'loft', furnished = false, note = '' },
    ['k4_loft3_shell'] = { pack = 'K4MB1 Exclusive', use = 'home', type = 'loft', furnished = false, note = '' },
    ['k4_manor1_shell'] = { pack = 'K4MB1 Exclusive', use = 'home', type = 'mansion', furnished = false, note = '' },
    ['k4_manor2_shell'] = { pack = 'K4MB1 Exclusive', use = 'home', type = 'mansion', furnished = false, note = '' },
    ['k4_modern1_shell'] = { pack = 'K4MB1 Exclusive', use = 'home', type = 'apartment', furnished = false, note = '' },
    ['k4_modern2_shell'] = { pack = 'K4MB1 Exclusive', use = 'home', type = 'apartment', furnished = false, note = '' },
    ['k4_modern3_shell'] = { pack = 'K4MB1 Exclusive', use = 'home', type = 'apartment', furnished = false, note = '' },
    ['k4_modern4_shell'] = { pack = 'K4MB1 Exclusive', use = 'home', type = 'apartment', furnished = false, note = '' },
    ['k4_modern5_shell'] = { pack = 'K4MB1 Exclusive', use = 'home', type = 'apartment', furnished = false, note = '' },
    ['k4_modern6_shell'] = { pack = 'K4MB1 Exclusive', use = 'home', type = 'apartment', furnished = false, note = '' },
    ['k4_modern7_shell'] = { pack = 'K4MB1 Exclusive', use = 'home', type = 'apartment', furnished = false, note = '' },
    ['k4_modern8_shell'] = { pack = 'K4MB1 Exclusive', use = 'home', type = 'apartment', furnished = false, note = '' },
    ['k4_modern9_shell'] = { pack = 'K4MB1 Exclusive', use = 'home', type = 'apartment', furnished = false, note = '' },
    ['k4_modern10_shell'] = { pack = 'K4MB1 Exclusive', use = 'home', type = 'apartment', furnished = false, note = '' },
    ['k4_penthouse2_shell'] = { pack = 'K4MB1 Exclusive', use = 'home', type = 'penthouse', furnished = false, note = '' },
    ['k4_penthouse_shell'] = { pack = 'K4MB1 Exclusive', use = 'home', type = 'penthouse', furnished = false, note = '' },
    ['k4_vwmansion2a_shell'] = { pack = 'K4MB1 Exclusive', use = 'home', type = 'mansion', furnished = false, note = '' },
    ['k4_vwmansion2b_shell'] = { pack = 'K4MB1 Exclusive', use = 'home', type = 'mansion', furnished = false, note = '' },
    ['k4_vwmansion3_shell'] = { pack = 'K4MB1 Exclusive', use = 'home', type = 'mansion', furnished = false, note = '' },
    ['k4_vwmansion4b_shell'] = { pack = 'K4MB1 Exclusive', use = 'home', type = 'mansion', furnished = false, note = '' },
    ['k4_vwmansion4_shell'] = { pack = 'K4MB1 Exclusive', use = 'home', type = 'mansion', furnished = false, note = '' },
    ['k4_vwmansion5_shell'] = { pack = 'K4MB1 Exclusive', use = 'home', type = 'mansion', furnished = false, note = '' },
    ['k4_vwmansion6_shell'] = { pack = 'K4MB1 Exclusive', use = 'home', type = 'mansion', furnished = false, note = '' },
    ['k4_vwmansion7_shell'] = { pack = 'K4MB1 Exclusive', use = 'home', type = 'mansion', furnished = false, note = '' },
    ['k4_basement1_shell'] = { pack = 'K4MB1 Misc', use = 'work', type = 'basement', furnished = false, note = '' },
    ['k4_basement2_shell'] = { pack = 'K4MB1 Misc', use = 'work', type = 'basement', furnished = false, note = '' },
    ['k4_basement3_shell'] = { pack = 'K4MB1 Misc', use = 'work', type = 'basement', furnished = false, note = '' },
    ['k4_basement4_shell'] = { pack = 'K4MB1 Misc', use = 'work', type = 'basement', furnished = false, note = '' },
    ['k4_basement5_shell'] = { pack = 'K4MB1 Misc', use = 'work', type = 'basement', furnished = false, note = '' },
    ['k4_biker1_shell'] = { pack = 'K4MB1 Misc', use = 'work', type = 'clubhouse', furnished = false, note = '' },
    ['k4_biker2_shell'] = { pack = 'K4MB1 Misc', use = 'work', type = 'clubhouse', furnished = false, note = '' },
    ['k4_biker3_shell'] = { pack = 'K4MB1 Misc', use = 'work', type = 'clubhouse', furnished = false, note = '' },
    ['k4_container_shell'] = { pack = 'K4MB1 Misc', use = 'work', type = 'container', furnished = false, note = '' },
    ['k4_office1_shell'] = { pack = 'K4MB1 Misc', use = 'work', type = 'office', furnished = false, note = '' },
    ['k4_office2_shell'] = { pack = 'K4MB1 Misc', use = 'work', type = 'office', furnished = false, note = '' },
    ['k4_office3_shell'] = { pack = 'K4MB1 Misc', use = 'work', type = 'office', furnished = false, note = '' },
    ['k4_office4_shell'] = { pack = 'K4MB1 Misc', use = 'work', type = 'office', furnished = false, note = '' },
    ['k4_office5_shell'] = { pack = 'K4MB1 Misc', use = 'work', type = 'office', furnished = false, note = '' },
    ['k4_office6_shell'] = { pack = 'K4MB1 Misc', use = 'work', type = 'office', furnished = false, note = '' },
    ['k4_office7_shell'] = { pack = 'K4MB1 Misc', use = 'work', type = 'office', furnished = false, note = '' },
    ['k4_office8_shell'] = { pack = 'K4MB1 Misc', use = 'work', type = 'office', furnished = false, note = '' },
    ['k4_stashhouse1_shell'] = { pack = 'K4MB1 Misc', use = 'crime', type = 'stash house', furnished = false, note = '' },
    ['k4_stashhouse2_shell'] = { pack = 'K4MB1 Misc', use = 'crime', type = 'stash house', furnished = false, note = '' },
    ['k4_storage_shell'] = { pack = 'K4MB1 Misc', use = 'work', type = 'storage', furnished = false, note = '' },
    ['k4_store1_shell'] = { pack = 'K4MB1 Misc', use = 'work', type = 'store', furnished = false, note = '' },
    ['k4_store2_shell'] = { pack = 'K4MB1 Misc', use = 'work', type = 'store', furnished = false, note = '' },
    ['k4_store3_shell'] = { pack = 'K4MB1 Misc', use = 'work', type = 'store', furnished = false, note = '' },
    ['k4_store4_shell'] = { pack = 'K4MB1 Misc', use = 'work', type = 'store', furnished = false, note = '' },
    ['k4_store5_shell'] = { pack = 'K4MB1 Misc', use = 'work', type = 'store', furnished = false, note = '' },
    ['k4_studio_shell'] = { pack = 'K4MB1 Misc', use = 'work', type = 'studio', furnished = false, note = '' },
    ['k4_textile_shell'] = { pack = 'K4MB1 Misc', use = 'work', type = 'workshop', furnished = false, note = '' },
    ['k4_truckwarehouse_shell'] = { pack = 'K4MB1 Misc', use = 'work', type = 'warehouse', furnished = false, note = '' },
    ['k4_warehouse1_shell'] = { pack = 'K4MB1 Misc', use = 'work', type = 'warehouse', furnished = false, note = '' },
    ['k4_warehouse2_shell'] = { pack = 'K4MB1 Misc', use = 'work', type = 'warehouse', furnished = false, note = '' },
    ['k4_warehouse3_shell'] = { pack = 'K4MB1 Misc', use = 'work', type = 'warehouse', furnished = false, note = '' },
    ['k4_warehouse4_shell'] = { pack = 'K4MB1 Misc', use = 'work', type = 'warehouse', furnished = false, note = '' },
    ['k4_warehouse5_shell'] = { pack = 'K4MB1 Misc', use = 'work', type = 'warehouse', furnished = false, note = '' },
    ['k4_warehouse6_shell'] = { pack = 'K4MB1 Misc', use = 'work', type = 'warehouse', furnished = false, note = '' },
    ['k4_bunker_shell'] = { pack = 'K4MB1 Illegal Ops', use = 'crime', type = 'bunker', furnished = false, note = '' },
    ['k4_container2_shell'] = { pack = 'K4MB1 Illegal Ops', use = 'work', type = 'container', furnished = false, note = '' },
    ['k4_guns_shell'] = { pack = 'K4MB1 Illegal Ops', use = 'crime', type = 'gun workshop', furnished = false, note = '' },
    ['k4_hideout_shell'] = { pack = 'K4MB1 Illegal Ops', use = 'crime', type = 'hideout', furnished = false, note = '' },
    ['k4_labacid_shell'] = { pack = 'K4MB1 Illegal Ops', use = 'crime', type = 'drug lab', furnished = false, note = '' },
    ['k4_labcoke2_shell'] = { pack = 'K4MB1 Illegal Ops', use = 'crime', type = 'drug lab', furnished = false, note = '' },
    ['k4_labcoke_shell'] = { pack = 'K4MB1 Illegal Ops', use = 'crime', type = 'drug lab', furnished = false, note = '' },
    ['k4_labempty2b_shell'] = { pack = 'K4MB1 Illegal Ops', use = 'crime', type = 'drug lab', furnished = false, note = '' },
    ['k4_labempty2_shell'] = { pack = 'K4MB1 Illegal Ops', use = 'crime', type = 'drug lab', furnished = false, note = '' },
    ['k4_labempty3_shell'] = { pack = 'K4MB1 Illegal Ops', use = 'crime', type = 'drug lab', furnished = false, note = '' },
    ['k4_labempty4_shell'] = { pack = 'K4MB1 Illegal Ops', use = 'crime', type = 'drug lab', furnished = false, note = '' },
    ['k4_labempty_shell'] = { pack = 'K4MB1 Illegal Ops', use = 'crime', type = 'drug lab', furnished = false, note = '' },
    ['k4_labmeth2_shell'] = { pack = 'K4MB1 Illegal Ops', use = 'crime', type = 'drug lab', furnished = false, note = '' },
    ['k4_labmeth_shell'] = { pack = 'K4MB1 Illegal Ops', use = 'crime', type = 'drug lab', furnished = false, note = '' },
    ['k4_labweed2_shell'] = { pack = 'K4MB1 Illegal Ops', use = 'crime', type = 'drug lab', furnished = false, note = '' },
    ['k4_labweed_shell'] = { pack = 'K4MB1 Illegal Ops', use = 'crime', type = 'drug lab', furnished = false, note = '' },
    ['k4_laundry_shell'] = { pack = 'K4MB1 Illegal Ops', use = 'crime', type = 'money laundry', furnished = false, note = '' },
    ['k4_stashhouse3_shell'] = { pack = 'K4MB1 Illegal Ops', use = 'crime', type = 'stash house', furnished = false, note = '' },
    ['k4_stashhouse4_shell'] = { pack = 'K4MB1 Illegal Ops', use = 'crime', type = 'stash house', furnished = false, note = '' },
    ['k4_garage1_shell'] = { pack = 'K4MB1 Garages', use = 'work', type = 'garage', furnished = false, note = '' },
    ['k4_garage2_shell'] = { pack = 'K4MB1 Garages', use = 'work', type = 'garage', furnished = false, note = '' },
    ['k4_garage3_shell'] = { pack = 'K4MB1 Garages', use = 'work', type = 'garage', furnished = false, note = '' },
    ['k4_garage4_shell'] = { pack = 'K4MB1 Garages', use = 'work', type = 'garage', furnished = false, note = '' },
    ['k4_garage5_shell'] = { pack = 'K4MB1 Garages', use = 'work', type = 'garage', furnished = false, note = '' },
    ['k4_garage6_shell'] = { pack = 'K4MB1 Garages', use = 'work', type = 'garage', furnished = false, note = '' },
    ['k4_garage7_shell'] = { pack = 'K4MB1 Garages', use = 'work', type = 'garage', furnished = false, note = '' },
    ['k4_garage8_shell'] = { pack = 'K4MB1 Garages', use = 'work', type = 'garage', furnished = false, note = '' },
    ['k4_garage9_shell'] = { pack = 'K4MB1 Garages', use = 'work', type = 'garage', furnished = false, note = '' },
    ['k4_garage10_shell'] = { pack = 'K4MB1 Garages', use = 'work', type = 'garage', furnished = false, note = '' },
    ['apart_luxe_1'] = { pack = 'Jordqn free', use = 'home', type = 'apartment', furnished = true, note = 'luxury' },
    ['motel_low'] = { pack = 'Jordqn free', use = 'home', type = 'motel room', furnished = true, note = 'low tier' },
    ['warehouse_small'] = { pack = 'Jordqn free', use = 'work', type = 'warehouse', furnished = true, note = 'small' },
    ['coke_business_empty'] = { pack = 'Jordqn free', use = 'crime', type = 'drug lab', furnished = false, note = 'empty drug lab' },
    ['finals_modernloftv1'] = { pack = 'Finals', use = 'home', type = 'loft', furnished = true, note = 'modern loft' },
    ['mv_sh_01_subhampro_tebex_io'] = { pack = 'Subham', use = 'unk', type = 'not checked', furnished = false, note = 'modern shell; type needs a look in game' },
    ['mv_sh_02_subhampro_tebex_io'] = { pack = 'Subham', use = 'unk', type = 'not checked', furnished = false, note = '' },
    ['m_sh_01_subhampro_tebex_io'] = { pack = 'Subham', use = 'unk', type = 'not checked', furnished = false, note = '' },
    ['m_sh_02_subhampro_tebex_io'] = { pack = 'Subham', use = 'unk', type = 'not checked', furnished = false, note = '' },
    ['m_sh_03_subhampro_tebex_io'] = { pack = 'Subham', use = 'unk', type = 'not checked', furnished = false, note = '' },
    ['m_sh_04_subhampro_tebex_io'] = { pack = 'Subham', use = 'unk', type = 'not checked', furnished = false, note = '' },
    ['m_sh_05_subhampro_tebex_io'] = { pack = 'Subham', use = 'unk', type = 'not checked', furnished = false, note = '' },
    ['m_sh_06_subhampro_tebex_io'] = { pack = 'Subham', use = 'unk', type = 'not checked', furnished = false, note = '' },
    ['m_sh_07_subhampro_tebex_io'] = { pack = 'Subham', use = 'unk', type = 'not checked', furnished = false, note = '' },
    ['m_sh_08_subhampro_tebex_io'] = { pack = 'Subham', use = 'unk', type = 'not checked', furnished = false, note = '' },
    ['m_sh_09_subhampro_tebex_io'] = { pack = 'Subham', use = 'unk', type = 'not checked', furnished = false, note = '' },
    ['d3_shell_shellv1'] = { pack = 'NavyPanda', use = 'unk', type = 'not checked', furnished = false, note = 'type needs a look in game' },
    ['d3_shell_shellv2'] = { pack = 'NavyPanda', use = 'unk', type = 'not checked', furnished = false, note = '' },
    ['d3_shell_shellv3'] = { pack = 'NavyPanda', use = 'unk', type = 'not checked', furnished = false, note = '' },
    ['mv13_shell_demo1'] = { pack = 'Maruii', use = 'unk', type = 'not checked', furnished = false, note = 'type needs a look in game' },
    ['mv13_shell_demo2'] = { pack = 'Maruii', use = 'unk', type = 'not checked', furnished = false, note = '' },
    ['mv13_shell_demo3'] = { pack = 'Maruii', use = 'unk', type = 'not checked', furnished = false, note = '' },
    ['pata_shell5'] = { pack = 'Pata', use = 'unk', type = 'not checked', furnished = false, note = 'type needs a look in game' },
}
